[files]
extend-exclude = [
    ".git/",
    ".github/",
    "__MACOSX/",
    ".DS_Store",
    "node_modules/",
    "dist/",
    "apis/",
    "*.tsbuildinfo",
    "*.log",
    "pnpm-debug.log*",
]

[default.extend-words]
splitted = "splitted"
